language: node_js
node_js:
 - '6'
before_script:
 - npm run setup
script:
 - gulp integrate
before_deploy:
 - git config --global push.default matching
 - git config --global user.email "franciscomerdot@gmail.com"
 - git config --global user.name "Travis-CI"
 - git config credential.helper "store --file=.git/credentials"
 - echo "https://${GitHub_Token}:@github.com" > .git/credentials
deploy:
 - provider: script
   script: gulp deploy
   on:
    tags: true